### ISSUE TITLE
Problems Installing - fix suggested

### ISSUE THREAD

**Issue by CJYate** [samfoo/noobhack#10]
I had problems installing the software.  I modified the setup.py file and seem to have fixed the problem

For what it's worth I'm using Python 2.6.7 on Debian wheezy/sid

Not sure whether I can commit the change directly, so here's my patch:

--- setup.py    2011-08-20 00:10:19.000000000 +0100
+++ ../setup.py 2011-08-20 00:03:36.000000000 +0100
@@ -9,7 +9,7 @@
     description="noobhack helps you ascend at nethack",
     long_description=open("readme.md", "r").read(),
     requires=["vt102 (>=0.3.2)"],
-    packages=["noobhack"],
-    scripts=["noobhack/noobhack"],
-    packages=["noobhack", "noobhack.game"],
-    scripts=["scripts/noobhack"],
   license="Lesser General Public License v3.0"
  )

---

New version should read:

from distutils.core import setup

setup(
    name="noobhack",
    version="0.3",
    author="Sam Gibson",
    author_email="sam@ifdown.net",
    url="https://github.com/samfoo/noobhack",
    description="noobhack helps you ascend at nethack",
    long_description=open("readme.md", "r").read(),
    requires=["vt102 (>=0.3.2)"],
    packages=["noobhack", "noobhack.game"],
    scripts=["scripts/noobhack"],
    license="Lesser General Public License v3.0"
)

**Comment by samfoo** [comment]
Hey,

Im on my phone, so sorry for the brevity.

I would suggest switching to the noobhack-0.3 branch. Its currently
the most stable and has the newest bug fixes, including fixing install
issues (I hope).

Let me know if that works for you. I've been meaning to finish the
roadmap and merge back to master anyway.

Sam Gibson

On 8/19/11, CJBrew
reply@reply.github.com
wrote:

**Comment by CJYate** [comment]
Hi Sam, 
Unless I'm mistaken I'm on that branch. Maybe the setup.py in 0.3 isn't working for me because of a mismatch of Python versions or something -- but I had to add the noobhack.game module and change the script directory to get things to work straight out of the box.
cheers, Chris

**Comment by samfoo** [comment]
Fixed. Thanks for the patch. Sorry it took so long, I'm in the process of moving and having had much free time.
