### ISSUE TITLE
Highlighting/colouring text

### ISSUE THREAD

**Issue by CJYate** [samfoo/noobhack#14]
Hi Samfoo, 

Something I saw in Interhack but I thought was quite nice was the ability to highlight specific words (e.g. "blessed" in an inventory).  This is an improvement on the 'standard' menucolors patch, which only lets you specify colours for the whole line (if I remember correctly).

I've put a little mod together which adds some lines to the ui.py _redraw_row function, in order to colour the text based on regular expressions.  An additional file is included (colorpatterns.py) that specifies the regex patterns and colors/styles to use.  

Hopefully you can get the code mods from https://github.com/CJBrew/noobhack/tree/inline_highlights.  I would have submitted a pull request but I don't know whether you like the idea or not... ;-)

If you look at colorpatterns.py it should be fairly obvious how this work could be extended.  I've only put in a handful of definitions, as I suspect this is something that might be left user-definable (or perhaps configured to _your_ own tastes..!)

cheers

Chris

**Comment by samfoo** [comment]
I've moved HP highlighting to a plugin. It should now be reasonably trivial to add any additional plugins that highlight text in the same way.

See the code here for details: https://github.com/samfoo/noobhack/blob/master/noobhack/game/plugins/hp_color/__init__.py

I'll take a look at adding the blessed, cursed, uncursed modifiers.
