### ISSUE TITLE
Pets don't get highlighted

### ISSUE THREAD

**Issue by TjrGithub** [samfoo/noobhack#8]
OPTIONS=hilite_pet
doesn't seem to have any effect.

I start it this way:
nohup xterm -fa Monaco -fs 14 -fg white -bg black &
screen -S playtjr -c ~/.screenrc-pacifist  ./scripts/noobhack --crumbs -h nethack.alt.org

Mac OS X 10.5.8. Screen remaps some keys, has no effect on the actual bug.

And use this config file:
http://alt.org/nethack/userdata/t/tjr3/tjr3.nh343rc

**Comment by samfoo** [comment]
> OPTIONS=hilite_pet

This should work now.
