### ISSUE TITLE
need to refresh screen once per keystroke when playing through screen

### ISSUE THREAD

**Issue by TjrGithub** [samfoo/noobhack#9]
When I use screen to remap the movement keys, I need to press control-r (refresh screen) once per keystroke in order for the display to be updated properly. The farlook command ";" is a good way to demonstrate this quirk: the cursor as displayed always seems to lag one keystroke. Strangely, GNU screen with an empty config file doesn't exhibit this bug, but a screen config with only remapping commands does. I have no idea in which software the bug is.

Commands to start session:
nohup xterm -fa Monaco -fs 14 -fg white -bg black &
unset PYTHONPATH ; export PYTHONPATH=pwd:$PYTHONPATH:scripts/noobhack
screen -S playtjr -c ~/.screenrc-pacifist  ./scripts/noobhack --crumbs -h nethack.alt.org

Simple .screenrc-pacifist to reproduce this bug:
bindkey 'h' stuff 'mh'

NAO config file:
http://alt.org/nethack/userdata/t/tjr3/tjr3.nh343rc

Steps to reproduce:
Start up a game as above, then farlook to the left, using the "h" key to move the curor. I would expect the highlighted square to move n times when hitting "h" n times, but it does only n-1 times.

**Comment by samfoo** [comment]
I believe this was fixed in the 0.3 release. There were some issues with stdin being buffered that screen was probably seeing more often than anything else.

See 012c7346bf4 for details.
